services:
  tunnel-server: &tunnel
    image: silvanei/tunnel:dev
    container_name: "tunnel-server"
    environment:
      - TZ=America/Sao_Paulo,
      - XDEBUG_MODE=off
    restart: unless-stopped
    command: php bin/server.php
    working_dir: /app
    volumes:
      - ./:/app

  tunnel-client:
    profiles:
      - dev
    <<: *tunnel
    container_name: "tunnel-client"
    command: php bin/client.php
    ports:
      - "127.0.0.1:9505:9505"
    depends_on:
      - tunnel-server
      - echo-server
  
  echo-server:
    profiles:
      - dev
    <<: *tunnel
    container_name: "echo-server"
    command: php .docker/echo-server/echo-server.php
    environment:
      - LOG_LEVEL=Debug
