services:
  tunnel-server: &tunnel
    image: silvanei/tunnel:dev
    container_name: "tunnel-server"
    environment:
      - TZ=America/Sao_Paulo,
      - XDEBUG_MODE=off
    restart: unless-stopped
    command: php bin/server.php
    working_dir: /app
    volumes:
      - ./:/app
  nginx:
    profiles:
      - dev
    image: nginx:latest
    container_name: "nginx"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "9500:9500"
    restart: unless-stopped
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  tunnel-client:
    profiles:
      - dev
    <<: *tunnel
    container_name: "tunnel-client"
    command: php client/bin/server.php
    ports:
      - "127.0.0.1:9505:9505"
  
  echo-server:
    profiles:
      - dev
    <<: *tunnel
    container_name: "echo-server"
    command: php .docker/echo-server/echo-server.php
